Hw2 tests
GenesisEducationKyiv/main-project-timofeyka25 pull request #5
Opened 2023-06-23 09:55 UTC by timofeyka25

Реалізовано unit, integration та e2e тести. В юніт тестах використано моки, згенеровані за допомогою пакету 
`github.com/golang/mock/gomock`. Для тестування відправки мейлів за допомогою smtp використано фейк сервіс [mailtrap.io](https://mailtrap.io), який імітує роботу реального smtp серверу, але зберігає всі надіслані листи замість надсилання на реальні пошти. Е2е тести вже були реалізовані за допомогою postman тестів, але додав ще імплементацію на go, використавши пакет httptest.

2023-06-25 09:58 UTC, dmmitrenko approved these changes
здається усі тести написана добре, слідують принципам FIRST, зауважень немає у мене

2023-06-27 22:43 UTC, oleksandr-kh requested changes
В цілому молодець, гарно попрацював
сподобались
- юніт тести
- інтеграційний
- е2е які в постман, в го треба переробити
і треба щоб тести проходили))

2023-06-27 22:43 UTC, oleksandr-kh commented on go.mod
> +go 1.19
можна було go 1.20 вже використовувати 😉

2023-06-27 22:43 UTC, oleksandr-kh commented on src/app/handler/newsletter_handler_e2e_test.go
> +			name:               "Subscribe successful",
на даний момент тест не проходить
        	            	expected: 200
        	            	actual  : 409

2023-06-27 22:43 UTC, oleksandr-kh commented on src/app/handler/newsletter_handler_e2e_test.go
> +			name:               "Send emails successful",
На даний момент тест не проходить
        	            	expected: 200
        	            	actual  : 400

2023-06-27 22:43 UTC, oleksandr-kh commented on src/app/handler/exchange_handler_e2e_test.go
> +			api.Get("/rate", exchangeHandler.GetCurrencyRate)
в тебе e2e тести - не зовсім e2e
більше схожі на інтеграційні, але ще й модифіковані
Для правильних е2е гарно було б підіймати апку по типу як ти це робиш в main.go і вже на ній тестувати
В твоєму ж випадку ти навіть в тесті реєструєш ендпоінт. Якщо у файлі src/app/handler/init_routes.go ти змінеш роути, то тест в тебе всеодно буде проходити 🤷‍♂️

2023-06-29 13:16 UTC, timofeyka25 commented on go.mod
> +go 1.19
вже в наступній домашці перейду ;)

2023-06-29 13:16 UTC, timofeyka25 commented on src/app/handler/newsletter_handler_e2e_test.go
> +			name:               "Subscribe successful",
пофіксив

2023-06-29 13:16 UTC, timofeyka25 commented on src/app/handler/newsletter_handler_e2e_test.go
> +			name:               "Send emails successful",
пофіксив

2023-06-29 13:16 UTC, timofeyka25 commented on src/app/handler/exchange_handler_e2e_test.go
> +			api.Get("/rate", exchangeHandler.GetCurrencyRate)
переробив

2023-06-30 10:34 UTC, merged